# Generated by Django 3.2.25 on 2024-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
