# Generated by Django 3.2.25 on 2024-04-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0002_alter_entries_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='priceChange',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
